-- Lookup tables
CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE age_rating (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Base account table
CREATE TABLE account (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role INT NOT NULL, -- 0 = customer, 1 = publisher, 2 = admin
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Customer table (1:1 with account)
CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL UNIQUE, -- has to ensure 1:1 relationship with account
    payment_method VARCHAR(100),
    address VARCHAR(255),
    CONSTRAINT fk_customer_account
        FOREIGN KEY (account_id) REFERENCES account(id) -- enforces 1:1 relationship with account, points to an existing, real ID
);

-- Publisher table (1:1 with account)
CREATE TABLE publisher (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL UNIQUE,
    studio_name VARCHAR(255) NOT NULL,
    amount_of_games INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_publisher_account
        FOREIGN KEY (account_id) REFERENCES account(id)
);

-- Game table
CREATE TABLE game (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    genre_id INT NOT NULL,
    age_rating_id INT NOT NULL,
    price NUMERIC(5,2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_game_publisher
        FOREIGN KEY (publisher_id) REFERENCES publisher(id),
    CONSTRAINT fk_game_genre
        FOREIGN KEY (genre_id) REFERENCES genre(id),
    CONSTRAINT fk_game_age_rating
        FOREIGN KEY (age_rating_id) REFERENCES age_rating(id)
);

-- Orders table
CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_price NUMERIC(5,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customer(id)
);

-- Junction table for games in orders
CREATE TABLE order_games (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id INT NOT NULL,
    order_id INT NOT NULL,
    quantity INT NOT NULL,

    CONSTRAINT fk_order_games_game
        FOREIGN KEY (game_id) REFERENCES game(id),
    CONSTRAINT fk_order_games_order
        FOREIGN KEY (order_id) REFERENCES orders(id),

    CONSTRAINT ck_order_games_quantity CHECK (quantity >= 1),
    CONSTRAINT uq_order_games UNIQUE (game_id, order_id)
);

-- Reviews table
CREATE TABLE reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id INT NOT NULL,
    customer_id INT NOT NULL,
    rating INT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reviews_game
        FOREIGN KEY (game_id) REFERENCES game(id),
    CONSTRAINT fk_reviews_customer
        FOREIGN KEY (customer_id) REFERENCES customer(id),

    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 10),
    CONSTRAINT uq_reviews UNIQUE (game_id, customer_id)
);

-- Create Roles Table
CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

-- Create Permissions Table
CREATE TABLE permissions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

-- Create Role_Permissions mapping table
CREATE TABLE role_permissions (
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    permission_id INT REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- Create Account_Roles mapping table
CREATE TABLE account_roles (
    account_id INT REFERENCES account(id) ON DELETE CASCADE,
    role_id INT REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (account_id, role_id)
);


-- Insert the 3  Roles
INSERT INTO roles (id, name) VALUES 
(1, 'Admin'), 
(2, 'Publisher'), 
(3, 'Customer');

-- Insert all the Permissions we designed
INSERT INTO permissions (id, name) VALUES 
(1, 'cart.use'),
(2, 'orders.create'),
(3, 'orders.read.own'),
(4, 'orders.read.any'),
(5, 'library.read.own'),
(6, 'reviews.create'),
(7, 'reviews.delete.own'),
(8, 'reviews.delete.owngames'),
(9, 'reviews.delete.any'),
(10, 'reviews.moderate'),
(11, 'games.create'),
(12, 'games.update.own'),
(13, 'games.update.any'),
(14, 'games.delete.own'),
(15, 'games.delete.any'),
(16, 'publishers.approve'),
(17, 'analytics.read');

-- Give permissions to Admin (Role 1) -> Gets Admin stuff
INSERT INTO role_permissions (role_id, permission_id) VALUES 
(1, 4), (1, 9), (1, 10), (1, 11), (1, 13), (1, 15), (1, 16), (1, 17);

-- Give permissions to Publisher (Role 2) -> Gets Publisher stuff
INSERT INTO role_permissions (role_id, permission_id) VALUES 
(2, 8), (2, 11), (2, 12), (2, 14);

-- Give permissions to Customer (Role 3) -> Gets Customer stuff
INSERT INTO role_permissions (role_id, permission_id) VALUES 
(3, 1), (3, 2), (3, 3), (3, 5), (3, 6), (3, 7);

-- MIGRATE EXISTING USERS: Link current accounts to the new Roles
DELETE FROM account_roles;  -- clear any previously-migrated links

-- MIGRATE EXISTING USERS: Link your current accounts to the new Roles
-- Migrate existing Admins (account.role = 1 -> roles.id 1 (Admin))
INSERT INTO account_roles (account_id, role_id)
SELECT id, 1 FROM account WHERE role = 1;

-- Migrate existing Publishers (account.role = 2 -> roles.id 2 (Publisher))
INSERT INTO account_roles (account_id, role_id)
SELECT id, 2 FROM account WHERE role = 2;

-- Migrate existing Customers (account.role = 0 -> roles.id 3 (Customer))
INSERT INTO account_roles (account_id, role_id)
SELECT id, 3 FROM account WHERE role = 0;
 -- changed perm
UPDATE permissions 
SET name = 'reviews.read.owngames' 
WHERE name = 'reviews.delete.owngames';